/*!
 * cdp.nativebridge.d.ts 
 * This file is generated by the CDP package build process.
 *
 * Date: 2015-11-09T18:21:26
 */
/// <reference path="cdp.promise.d.ts" />
/// <reference path="cdp.plugin.nativebridge.d.ts" />
declare module CDP {
    module NativeBridge {
        import IPromise = CDP.IPromise;
        import Plugin = CDP.Plugin.NativeBridge;
        /**
         * \~english
         * @interface Feature
         * @brief feature information.
         *
         * \~japanese
         * @interface Feature
         * @brief 機能情報
         */
        interface Feature extends Plugin.Feature {
        }
        /**
         * \~english
         * @interface ConstructOptions
         * @brief NativeBridge class's consrtruction options.
         *
         * \~japanese
         * @interface ConstructOptions
         * @brief 初期化に指定するオプション
         */
        interface ConstructOptions extends Plugin.ConstructOptions {
        }
        /**
         * \~english
         * @interface IResult
         * @brief NativeBridge base result information.
         *
         * \~japanese
         * @interface IResult
         * @brief NativeBridge の基底 Result 情報
         */
        interface IResult extends Plugin.IResult {
        }
        /**
         * \~english
         * @interface ExecOptions
         * @brief exec() method options.
         *
         * \~japanese
         * @interface ExecOptions
         * @brief exec() に渡すオプション
         */
        interface ExecOptions extends Plugin.ExecOptions {
        }
        /**
         * \~english
         * @interface Promise
         * @brief Cancelable promise interface utilized from jquery promise.
         *
         * \~japanese
         * @interface Promise
         * @brief NativeBridge が扱う Promise オブジェクトの定義
         */
        interface Promise extends IPromise<IResult> {
        }
    }
}
declare module CDP {
    module NativeBridge {
        /**
         * \~english
         * @class Utils
         * @brief The utility class for CDP.NativeBridge.
         *
         * \~japanese
         * @class Utils
         * @brief CDP.NativeBridge が使用するユーティリティクラス
         */
        class Utils {
            private static s_pluginReady;
            /**
             * \~english
             * Defines error code map from the plugin result to CDP.NativeBridge result code.
             *
             * @param errorCode {String} [in] set result code string. ex): "SUCCESS_OK"
             *
             * \~japanese
             * plugin の Result Code を CDP.NativeBridge にマップする
             *
             * @param errorCode {String} [in] Result Code 文字列を指定 ex): "SUCCESS_OK"
             */
            static defineResultCode(errorCode: string): void;
            /**
             * \~english
             * Wait for cordova "deviceready" event fired.
             *
             * \~japanese
             * cordova が 使用可能になるまで待機
             */
            static waitForPluginReady(): JQueryPromise<void>;
            /**
             * \~english
             * Create NativeBridge.Promise object from jQueryDeferred object.
             *
             * @param df {JQueryDeferred} [in] set jQueryDeferred instance.
             * @return   {Promise} NativeBridge.Promise object.
             *
             * \~japanese
             * Promise オブジェクトの作成
             * jQueryDeferred オブジェクトから、NativeBridge.Promise オブジェクトを作成する
             *
             * @param df {JQueryDeferred} [in] jQueryDeferred instance を指定
             * @return   {Promise} NativeBridge.Promise オブジェクト
             */
            static makePromise(df: JQueryDeferred<IResult>): Promise;
            /**
             * \~english
             * Helper function to correctly set up the prototype chain, for subclasses.
             * The function behavior is same as extend() function of Backbone.js.
             *
             * @param protoProps  {Object} [in] set prototype properties as object.
             * @param staticProps {Object} [in] set static properties as object.
             * @return {Object} subclass constructor.
             *
             * \~japanese
             * クラス継承のためのヘルパー関数
             * Backbone.js extend() 関数と同等
             *
             * @param protoProps  {Object} [in] prototype properties をオブジェクトで指定
             * @param staticProps {Object} [in] static properties をオブジェクトで指定
             * @return {Object} サブクラスのコンストラクタ
             */
            static extend(protoProps: Object, staticProps?: Object): Object;
        }
    }
}
declare module CDP {
    module NativeBridge {
        var SUCCESS_OK: number;
        var SUCCESS_PROGRESS: number;
        var ERROR_FAIL: number;
        var ERROR_CANCEL: number;
        var ERROR_INVALID_ARG: number;
        var ERROR_NOT_IMPLEMENT: number;
        var ERROR_NOT_SUPPORT: number;
        var ERROR_INVALID_OPERATION: number;
        var ERROR_CLASS_NOT_FOUND: number;
        var ERROR_METHOD_NOT_FOUND: number;
        /**
         * \~english
         * @class Gate
         * @brief The base class for NativeBridge communication.
         *        You can derive any Gate class from this class.
         *
         * \~japanese
         * @class Gate
         * @brief NativeBridge と通信するベースクラス
         *        このクラスから任意の Gate クラスを派生して実装可能
         */
        class Gate {
            private _bridge;
            private static extend;
            /**
             * \~english
             * constructor
             *
             * @param feature {Feature}          [in] feature information.
             * @param options {ConstructOptions} [in] construction options.
             *
             * \~japanese
             * constructor
             *
             * @param feature {Feature}          [in] 初期化情報を指定
             * @param options {ConstructOptions} [in] オプションを指定
             */
            constructor(feature: Feature, options?: ConstructOptions);
            /**
             * \~english
             * Execute task.
             * the function calls the Native class method from correspondent method name.
             *
             * @param method  {String}       [in] method name of Native class
             * @param args    {Object[]}     [in] set arguments by array type.
             * @param options {ExecOptions?} [in] set exec options.
             * @return {Promise} NativeBridge.Promise object.
             *
             * \~japanese
             * タスクの実行
             * 指定した method 名に対応する Native Class の method を呼び出す。
             *
             * @param method  {String}       [in] Native Class のメソッド名を指定
             * @param args    {Object[]}     [in] 引数を配列で指定
             * @param options {ExecOptions?} [in] 実行オプションを指定
             * @return {Promise} NativeBridge.Promise オブジェクト
             */
            exec(method: string, args?: any[], options?: ExecOptions): Promise;
            /**
             * \~english
             * Cancel all tasks.
             *
             * @param options {ExecOptions?} [in] set execute options.
             * @return {jQueryPromise} jQuery.Promise object.
             *
             * \~japanese
             * すべてのタスクのキャンセル
             *
             * @param options {ExecOptions?} [in] 実行オプションを指定
             * @return {jQueryPromise} jQuery.Promise オブジェクト
             */
            cancel(options?: ExecOptions): JQueryPromise<IResult>;
            /**
             * \~english
             * Destruction for the instance.
             * release Native class reference. after that, exec() becomes invalid.
             *
             * @param options {ExecOptions?} [in] set execute options.
             * @return {jQueryPromise} jQuery.Promise object.
             *
             * \~japanese
             * インスタンスの破棄
             * Native の参照を解除する。以降、exec は無効となる。
             *
             * @param options {ExecOptions?} [in] 実行オプションを指定
             * @return {jQueryPromise} jQuery.Promise オブジェクト
             */
            dispose(options?: ExecOptions): JQueryPromise<IResult>;
            /**
             * \~english
             * Access to Plugin.NativeBridge object.
             * If you want to use low level exec(), you can use this accessor.
             *
             * @return {Plugin.NativeBridge} Plugin.NativeBridge instance.
             *
             * \~japanese
             * Plugin.NativeBridge オブジェクトへのアクセス
             * 低レベル exec() を使用したい場合に利用可能
             *
             * @return {Plugin.NativeBridge} Plugin.NativeBridge インスタンス.
             */
            protected bridge: Plugin.NativeBridge;
            private makeFatal();
        }
    }
}
