{
    "area": {
        "x": 0,
        "y": 0,
        "w": 480,
        "h": 812
    },
    "label": [{
        "area": {
            "x": 24,
            "y": 24,
            "w": 240,
            "h": 64
        },
        "text": "ラベル",
        "color": 0,
        "font": "SST",
        "size": 32
    }],
    "image": [{
        "area": {
            "x": 24,
            "y": 128,
            "w": 160,
            "h": 120
        },
        "path": "default_image.png"
    }]
}