{
    "area": {
        "x": 0,
        "y": 0,
        "w": 464,
        "h": 812
    },
    "label": [{
        "area": {
            "x": 8,
            "y": 0,
            "w": 464,
            "h": 87
        },
        "text": "TEXT LABEL",
        "color": 0,
	"font_weight" : "normal",
        "font": "SST",
        "size": 20
    }],
    "image": [{
        "area": {
            "x": 8,
            "y": 0,
            "w": 464,
            "h": 232
        },
        "path": "default_image.png"
    }]
}